name: Linting with Pylint
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks with pylint
    steps:

    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: "**/*.py"

    - uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - run: pip install --upgrade pip
    - run: pip install . --extra-index-url https://gitlab.com/api/v4/projects/40060814/packages/pypi/simple
    - run: pip install pylint==2.16.*
    - run: pylint --rcfile=pylintrc ${{ steps.changed-files.outputs.all_changed_files }}
