name: Python Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks unittest

    strategy:
      matrix:
        python-version: [3.6.x, 3.7.x, 3.8.x, 3.9.x, 3.10.x]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Python all python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - run: pip install --upgrade pip
      - run: pip install . --extra-index-url https://gitlab.com/api/v4/projects/40060814/packages/pypi/simple

      - name: Run Test
        run: python -m unittest discover tests
